# An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.
# Given a DNA string t corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u.
# Given: A DNA string t having length at most 1000 nt.
# Return: The transcribed RNA string of t.

# Define DNA sequence
seqDNA = "ATAGCTACGTCAACTCCATTAGCTTCCGGAACGCCATTGCTCCTCAACCTCTTGCTAGAGATCAGCGCTAGTTTTACGCAGACTGGTACCTATGACTGTTACTTGCTCGGTCCTGGTTACCTCTACTAGGCCGCGACGTTCCACACTACAGGCTTGATGGGCTATTGGATATGGCAGAGCCGAACTGGCAAATAATATGCTTGGCATCTAACCGGGTAGGTTGGATGAGCTATCGAGTAGAGTATCGACGCAAGTTCGTAGTACAGCTAGGATAGTCCTGTGGTAAAATCAATGTGGTAGAACTCTAGTACACCGAGTGCCAACCCTGGTAAAGGAATCTTTGCCGAGGGCGTCATATCGGGTGAGATGTTATGGCGACTGTAACTTCAGTCAATGAGTTGAATCGATTAACAAATGACGACGACGGACATGCTGGGATTTCTAGGAATCACGAGAGGTAACCTTTCAACGCTGGGCGGCCAACGATGTATATCCAGCTACCAGAATCGCGTTGCATTAAGTCCAATAATTAATCTTCTGCGATGCTACTGACCCGCGTATACCTGCTGCAATCTCTTATAGCGAGACAACACCGATTGCGAAGATAGAGTTGCACTGAATTTCCAACGTGTGGGCGTAGAAAATATTGCCACGTAACACCTAGAAGCGGACTGTAGAGGCGTTCATGACCAAGGCGATGTCCTGTGTGATCGACGCTCTAGTCAGATCTGGTCCAGCCAGACTAAATATCAGGTGAGCAGGTAGAGAGATTACCAACCTCGCGAAACTGGCCCGGGATTTGTTTGCCGCCGTGAGTAGCCGATTAAGTTGGCGCATTCCACGTCCCTGAGCCACGTTAACAGATCATTTGGTCTATTCCATGATCCTTTGCCCGCATGGCAGAGTTAGAAGCGGGTATTTAGCGACCCAACCGAGTT"

# Convert DNA sequence to RNA sequence using .replace method
seqRNA = seqDNA.replace("T", "U")

# Return RNA sequence
print(seqRNA)


